VNDK_SP_LIBRARIES := \
    android.hardware.graphics.allocator@2.0 \
    android.hardware.graphics.common@1.0 \
    android.hardware.graphics.common@1.1 \
    android.hardware.graphics.mapper@2.0 \
    android.hardware.graphics.mapper@2.1 \
    android.hardware.renderscript@1.0 \
    android.hidl.memory@1.0 \
    android.hidl.memory@1.0-impl \
    android.hidl.memory.token@1.0 \
    libbacktrace \
    libbase \
    libbcinfo \
    libblas \
    libc++ \
    libcompiler_rt \
    libcutils \
    libft2 \
    libhardware \
    libhidlbase \
    libhidlmemory \
    libhidltransport \
    libhwbinder \
    libhwbinder_noltopgo \
    libion \
    liblzma \
    libpng \
    libRSCpuRef \
    libRSDriver \
    libRS_internal \
    libunwind \
    libunwindstack \
    libutils \
    libutilscallstack \
    libui \
    libbinder \
    libz \
    libdexfile
